---
- name: Initializing Deployment
  shell: ssh {{ ebs_user }}@{{ hostname }} "source {{ env_file }} run && sh {{ applmgr_home }}/EBSscripts/ebs_init.sh --ct={{ custom_top }}"

- name: Deploy Database Objects (XXLE)
  shell: ssh {{ ebs_user }}@{{ hostname }} "source {{ env_file }} run && sh {{ applmgr_home }}/EBSscripts/XXLELOAD.sh -h {{ db_hostname }} -p {{ db_port }} --dbu1={{ db_user1 }} --dbp1={{ db_pass1 }} --dbs={{ db_service_name }}"

- name: Deploy Database Objects (APPS)
  shell: ssh {{ ebs_user }}@{{ hostname }} "source {{ env_file }} run && sh {{ applmgr_home }}/EBSscripts/APPSLOAD.sh -h {{ db_hostname }} -p {{ db_port }} --dbu2={{ db_user2 }} --dbp2={{ db_pass2 }} --dbs={{ db_service_name }}"
